### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by MuerteInHell** [o0johntam0o/phpBB-Extension-Codebox-Plus#13]
Hello, when I try to activate this extension on my phpBB 3.1.8 forum, it shows up as blank with following error: 
`Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "@o0johntam0o_codeboxplus/style.css" (looked into: ./ext/o0johntam0o/codeboxplus/styles/prosilver/template, ./ext/o0johntam0o/codeboxplus/styles/all/template, ./ext/o0johntam0o/codeboxplus/styles/all/template) in "@o0johntam0o_codeboxplus/event/overall_header_head_append.html" at line 1.' in /xxx/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:195 Stack trace: #0 /xxx/phpbb/template/twig/loader.php(107): Twig_Loader_Filesystem->findTemplate('@o0johntam0o_co...') #1 /xxx/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(138): phpbb\template\twig\loader->findTemplate('@o0johntam0o_co...') #2 /xxx/phpbb/template/twig/environment.php(202): Twig_Loader_Filesystem->getCacheKey('@o0johntam0o_co...') #3 /xxx/cache/twig/d/3/d3db33edfa99f5fdbd0e05ea2702056c367f285ce695114b5fc09d3520a81baf.php(24): phpbb\template\twig\ in /xxx/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 195
`

This extension would be extremely useful and I am looking forward to using it.

**Comment by o0johntam0o** [comment]
Hi MuerteInHell, please follow the instructions below:
1. Disable Codebox Plus
2. Delete Codebox Plus's data
3. Pure the phpBB's cache
4. Enable Codebox Plus

**Comment by MuerteInHell** [comment]
Hello o0johntam0o,

I have preformed those steps in that order but sadly the error remains.

**Comment by o0johntam0o** [comment]
Hi, what version of PHP you're working on? Are there any other extension installed in your board?
Note: phpBB 3.1.9 released (17/04/2016)

**Comment by MuerteInHell** [comment]
PHP 5.6.20

The only other extension I'm currently using is the following:
https://www.phpbb.com/community/viewtopic.php?t=2295956
